[package]
name = "WhisperMessenger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "websocket-server"
path = "src/main.rs"

[dependencies]
actix = "0.10"
actix-web = "3"
actix-web-actors = "3"
actix-files = "0.3"
actix-cors = "0.5.4"

diesel = { version = "1.4.8", features = ["postgres"] }

dotenv = "0.15.0"
bytes = "0.5"
byteorder = "1.3"
futures = "0.3"
env_logger = "0.8"
serde = "1"
serde_json = "1"
serde_with = { version = "1.12.0", features = ["json"]}
