[package]
name = "whisper"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.10"
actix-web = "3"
actix-web-actors = "3"
actix-files = "0.3"
actix-cors = "0.5.4"

chrono = "0.4.0"
diesel = { version = "1.4.8", features = ["postgres", "chrono"] }
diesel_migrations = "1"

dotenv = "0.15.0"
bytes = "0.5"
byteorder = "1.3"
futures = "0.3"
env_logger = "0.8"
serde = "1"
serde_json = "1"
serde_with = { version = "1.12.0", features = ["json"]}
# Needed for Postgres.
openssl = "*"
openssl-probe = "0.1.2"